 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:34:20] "POST /open_question HTTP/1.1" 200 -
 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
127.0.0.1 - - [04/Sep/2025 13:36:00] "POST /open_question HTTP/1.1" 200 -
 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
127.0.0.1 - - [04/Sep/2025 13:37:07] "POST /open_question HTTP/1.1" 200 -
 * Detected change in '/root/code/ai_based_education/test.py', reloading
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'Â¶ÇÊûúËÆ©‰Ω†ÊèèËø∞‰∏Ä‰∏ãÂ≠©Â≠êÁöÑÊÄßÊ†ºÔºà‰ºòÁÇπÂíåÁü≠ÊùøÔºâÔºå‰Ω†‰ºöÊÄéÊ†∑ÊèèËø∞Ôºü', 'answer': 'ÊàëËßâÂæóËá™Â∑±Êå∫ÂºÄÊúóÁöÑÔºåÊÑøÊÑèÂ∏ÆÂä©Âà´‰∫∫Ôºå‰ΩÜÊúâÊó∂ÂÄôÂ§™ÊÄ•Ë∫Å„ÄÇ'}]
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:38:07] "POST /instant_profile HTTP/1.1" 200 -
 * Detected change in '/root/code/ai_based_education/run_app.py', reloading
input_check_result: False
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:39:44] "POST /instant_profile HTTP/1.1" 200 -
 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:40:17] "POST /instant_profile HTTP/1.1" 200 -
 * Detected change in '/root/code/ai_based_education/test.py', reloading
input_check_result: False
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:40:44] "POST /swot HTTP/1.1" 200 -
 * Detected change in '/root/code/ai_based_education/test.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:42:05] "[35m[1mPOST /growth_advice HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 137, in produe_growth_advice
    rules = get_growth_advice_rules(request.json)
  File "/root/code/ai_based_education/main.py", line 72, in get_growth_advice_rules
    res['name'] = req['name']
KeyError: 'name'
 * Detected change in '/root/code/ai_based_education/run_app.py', reloading
input_check_result: False
<class 'int'>
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Serving Flask app 'run_app'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.25.21.92:5000
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:42:50] "POST /growth_advice HTTP/1.1" 200 -
198.235.24.34 - - [04/Sep/2025 13:42:50] "[33mGET / HTTP/1.1[0m" 404 -
 * Detected change in '/root/code/ai_based_education/test.py', reloading
input_check_result: False
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Detected change in '/root/code/ai_based_education/test.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Detected change in '/root/code/ai_based_education/test.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Detected change in '/root/code/ai_based_education/test.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
127.0.0.1 - - [04/Sep/2025 13:47:03] "POST /instant_profile HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [04/Sep/2025 13:55:26] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [04/Sep/2025 13:56:52] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [04/Sep/2025 13:57:38] "POST /open_question HTTP/1.1" 200 -
111.9.62.28 - - [04/Sep/2025 13:58:50] "POST /instant_profile HTTP/1.1" 200 -
111.9.62.28 - - [04/Sep/2025 14:00:42] "[31m[1mGET /swot HTTP/1.1[0m" 405 -
111.9.62.28 - - [04/Sep/2025 14:01:25] "[31m[1mGET /swot HTTP/1.1[0m" 405 -
111.9.62.28 - - [04/Sep/2025 14:01:33] "POST /swot HTTP/1.1" 200 -
111.9.62.28 - - [04/Sep/2025 14:02:52] "POST /growth_advice HTTP/1.1" 200 -
96.126.104.20 - - [04/Sep/2025 14:03:06] code 400, message Bad request version ('√¢')
96.126.104.20 - - [04/Sep/2025 14:03:06] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03\x08\x15√ú√£¬®n√ª√èM¬∞CJ`¬≥√ü~\x19\x09Lu\x0e\x09b\x83Ev$\x89¬Æulf f¬∂√§√û\x8b√ï\x17#¬•;7uX\x85√¢[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [04/Sep/2025 14:03:07] "[33mGET /signin HTTP/1.1[0m" 404 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [04/Sep/2025 14:04:29] "POST /open_question HTTP/1.1" 200 -
64.227.159.215 - - [04/Sep/2025 15:19:59] "[33mGET / HTTP/1.1[0m" 404 -
64.227.159.215 - - [04/Sep/2025 15:19:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
59.82.21.118 - - [04/Sep/2025 15:55:18] "[33mGET / HTTP/1.1[0m" 404 -
96.126.104.20 - - [04/Sep/2025 17:56:14] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [04/Sep/2025 17:56:14] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03\x16xm√™Q?GD√ê~l√®√ú√®\x0c¬¨\x07√§8\x0c¬≤√û√∏H¬≠¬æ√ÄS`X√Æa T√ó\x8eU\x06\x8dZF&#\x01v;p\x9eFpO\x8a9√à¬µ\x1d√≥√¢\x16√Ø¬Æ1√ü¬£^\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [04/Sep/2025 17:56:15] "[33mGET /signin HTTP/1.1[0m" 404 -
59.82.21.67 - - [04/Sep/2025 18:11:02] "[33mGET / HTTP/1.1[0m" 404 -
167.94.145.98 - - [04/Sep/2025 20:54:49] code 400, message Bad request version ('¬≥¬Æ\x8b\x1b√≤MQ\x04Ce)`√éB')
167.94.145.98 - - [04/Sep/2025 20:54:49] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03Oc√™a,f\x84¬∫<\x03fL√±√âl\x16\x15√°,\x1e\x05<\x0d\x87√µ=\x86\x9f#¬•¬∫√∂ ¬≥¬Æ\x8b\x1b√≤MQ\x04Ce)`√éB[0m" HTTPStatus.BAD_REQUEST -
167.94.145.98 - - [04/Sep/2025 20:54:52] "[33mGET / HTTP/1.1[0m" 404 -
167.94.145.98 - - [04/Sep/2025 20:54:56] "[33mGET / HTTP/1.1[0m" 404 -
167.94.145.98 - - [04/Sep/2025 20:54:57] code 505, message Invalid HTTP version (2.0)
167.94.145.98 - - [04/Sep/2025 20:54:57] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
167.94.145.98 - - [04/Sep/2025 20:55:01] code 505, message Invalid HTTP version (2.0)
167.94.145.98 - - [04/Sep/2025 20:55:01] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
167.94.145.98 - - [04/Sep/2025 20:55:02] "[33mGET /login HTTP/1.1[0m" 404 -
96.126.104.20 - - [04/Sep/2025 21:59:30] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [04/Sep/2025 21:59:30] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03<k\x907\x1e¬æsS?¬†i\x95OBv]√è\x92#¬¥\x08√Æ\x17\x03\x9f√í\x87√ã\x13¬©.c U√ü¬°0kZfR1\x14x√óU√ë√≤\x02+¬©¬π\x0f√ü\x0e\x97+\x8c√≠\x0b√æ\x17√Çr\x9d\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [04/Sep/2025 21:59:31] "[33mGET /signin HTTP/1.1[0m" 404 -
65.49.1.132 - - [04/Sep/2025 22:01:55] "[33mGET / HTTP/1.1[0m" 404 -
65.49.1.133 - - [04/Sep/2025 22:02:09] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
195.184.76.24 - - [04/Sep/2025 23:11:43] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x03\x01¬¶\x01\x00\x01¬¢\x03\x03\x9d\x8a¬ø*\x18i√ü\x82√∏√≥\x04√ù¬¥¬Ø√èL\x02√è\x13\x0e-\x86\x19√ì9√∏¬©6\x13¬Ø√í\x9e')
195.184.76.24 - - [04/Sep/2025 23:11:43] "[35m[1m\x16\x03\x03\x01¬¶\x01\x00\x01¬¢\x03\x03\x9d\x8a¬ø*\x18i√ü\x82√∏√≥\x04√ù¬¥¬Ø√èL\x02√è\x13\x0e-\x86\x19√ì9√∏¬©6\x13¬Ø√í\x9e \x95[0m" HTTPStatus.BAD_REQUEST -
195.184.76.110 - - [04/Sep/2025 23:11:47] "[33mGET / HTTP/1.1[0m" 404 -
195.184.76.166 - - [04/Sep/2025 23:24:10] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
91.196.152.101 - - [05/Sep/2025 01:41:50] code 400, message Bad request version ('√Ä#√Ä¬¨√Ä¬Æ√Ä+√Ä')
91.196.152.101 - - [05/Sep/2025 01:41:50] "[35m[1m\x16\x03\x03\x01¬¶\x01\x00\x01¬¢\x03\x03¬§8\x7f@?*=¬§√∫√ö"=\x90\x9f\x8c√ø#\x0f√∏.¬≠!\x7f¬§\x99U√≥K√£\x9d¬∂, (√πB¬¢\x18#5√¥√é\x15O\x03y\x87\x8d√£√´√ú9√≥√î√≥\x0c\x81√øk}E\x9dB¬™\x84\x00\x8a\x00\x16\x003\x00g√Ä\x9e√Ä¬¢\x00\x9e\x009\x00k√Ä\x9f√Ä¬£\x00\x9f\x00E\x00¬æ\x00\x88\x00√Ñ\x00\x9a√Ä\x08√Ä\x09√Ä#√Ä¬¨√Ä¬Æ√Ä+√Ä[0m" HTTPStatus.BAD_REQUEST -
91.196.152.14 - - [05/Sep/2025 01:41:55] "[33mGET / HTTP/1.1[0m" 404 -
91.196.152.101 - - [05/Sep/2025 01:50:52] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
196.251.86.195 - - [05/Sep/2025 01:50:58] code 400, message Bad request syntax ('\x05\x02\x00\x02')
196.251.86.195 - - [05/Sep/2025 01:50:58] "[35m[1m\x05\x02\x00\x02[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 02:04:30] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [05/Sep/2025 02:04:30] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03√π\x11\x91√®√æ\x0f<M~√Ñ2¬§n\x97√ª¬≤c(√í√£;\x97\x04√∂f√≤¬¥\x95$L\x8eE \x85√®F√πZv√É\x98\x14A\x99√†F\x11l-^S\x08}√ß;√©Z√ùj√Å√†√å√Æ√æ|\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 02:04:31] "[33mGET /signin HTTP/1.1[0m" 404 -
147.185.133.149 - - [05/Sep/2025 04:05:16] code 400, message Bad request version ('√Ä\x13√Ä')
147.185.133.149 - - [05/Sep/2025 04:05:16] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03¬®√§F\x9cN√òo√Ç¬¨|√åt√Å¬©j√ó√î\x98+√≤\x1f\x08¬≠¬≤\x1b\x1a\x1e¬Ω+\x1f ¬µ \x87\x0fI√õ,<\x9bJ\x83¬±)√Ñ\x82√∂8K√ß\x07_√û√ô1\x1f¬Æ\x87¬π$√ø=\x19g"\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
147.185.133.149 - - [05/Sep/2025 04:05:16] code 400, message Bad request version ('√Ä(√Ä$√Ä\x14√Ä')
147.185.133.149 - - [05/Sep/2025 04:05:16] "[35m[1m\x16\x03\x01\x00√ä\x01\x00\x00√Ü\x03\x03#√ä√ç\x07T\x00\x97&Y,\x98¬°$\x9a √º¬ªr√à4l√ß\x01¬πr\x92\x0b?Hn\x7f¬∏\x00\x00h√å\x14√å\x13√Ä/√Ä+√Ä0√Ä,√Ä\x11√Ä\x07√Ä'√Ä#√Ä\x13√Ä\x09√Ä(√Ä$√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
205.210.31.19 - - [05/Sep/2025 04:08:39] "[33mGET / HTTP/1.1[0m" 404 -
96.126.104.20 - - [05/Sep/2025 05:59:25] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [05/Sep/2025 05:59:25] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03¬™¬∞N\x82v>√íg\x90√ª√Ω√≠√ô\x12J√ä¬≥\x881o\x7feU\x18\x9e<y9√ü¬¢p√≠ f\x13¬†e\x153¬©√ú\x97√ó\x0f√ø)¬∂?¬Ø\x80\x01\x1b[\x86la√ö"√ê√æ\x0214Dj\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 05:59:26] "[33mGET /signin HTTP/1.1[0m" 404 -
198.235.24.13 - - [05/Sep/2025 08:01:03] "[33mGET / HTTP/1.0[0m" 404 -
66.175.213.4 - - [05/Sep/2025 08:14:46] code 400, message Bad request syntax ('\x16\x03\x01\x01')
66.175.213.4 - - [05/Sep/2025 08:14:46] "[35m[1m\x16\x03\x01\x01[0m" HTTPStatus.BAD_REQUEST -
66.175.213.4 - - [05/Sep/2025 08:14:46] code 400, message Bad request syntax ('\x16\x03\x01\x01')
66.175.213.4 - - [05/Sep/2025 08:14:46] "[35m[1m\x16\x03\x01\x01[0m" HTTPStatus.BAD_REQUEST -
198.235.24.42 - - [05/Sep/2025 08:33:47] "[33mGET / HTTP/1.1[0m" 404 -
45.33.14.5 - - [05/Sep/2025 08:37:16] "[33mGET / HTTP/1.1[0m" 404 -
172.236.127.133 - - [05/Sep/2025 08:37:31] "[33mGET / HTTP/1.1[0m" 404 -
 * Detected change in '/root/code/ai_based_education/prompt_template.py', reloading
input_check_result: False
eval_result ËØÑÊµãÁªìÊûúÔºåÂíådemoÊ†ºÂºè‰øùÊåÅ‰∏ÄËá¥Âç≥ÂèØ
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'ÈóÆÈ¢ò', 'answer': 'Á≠îÊ°à'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'ÈóÆÈ¢ò', 'answer': 'Á≠îÊ°à'}]
input_check_result: False
input_check_result: False
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'ÈóÆÈ¢ò', 'answer': 'Á≠îÊ°à'}]
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
 * Detected change in '/root/code/ai_based_education/main.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 995-271-986
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 09:08:22] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
47.96.17.121 - - [05/Sep/2025 09:10:54] "POST /open_question HTTP/1.1" 200 -
116.62.170.223 - - [05/Sep/2025 09:11:55] "POST /instant_profile HTTP/1.1" 200 -
47.111.13.228 - - [05/Sep/2025 09:12:00] "POST /swot HTTP/1.1" 200 -
47.110.249.186 - - [05/Sep/2025 09:12:06] "POST /growth_advice HTTP/1.1" 200 -
116.62.78.94 - - [05/Sep/2025 09:19:04] "POST /growth_advice HTTP/1.1" 200 -
96.126.104.20 - - [05/Sep/2025 10:02:07] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [05/Sep/2025 10:02:07] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x032\x11T2MfX\x9b\x8e\x1e√´√§|\x85s?√ò√æ\x94i)\x93√É\x0b\x03√å¬∞\x9f?\x9b¬∫? %D √º6\x92)eE√¥5√•0\x18√±J√ø√¨√£√î!√†¬∞g√Ñ√ø\x7f\x1b()√Ω√É\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 10:02:08] "[33mGET /signin HTTP/1.1[0m" 404 -
178.159.37.112 - - [05/Sep/2025 10:26:37] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*√†\x00\x00\x00\x00\x00Cookie:')
178.159.37.112 - - [05/Sep/2025 10:26:37] "[35m[1m\x03\x00\x00/*√†\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
2.57.122.89 - - [05/Sep/2025 10:47:23] code 400, message Bad request syntax ('SSH-2.0-Go')
2.57.122.89 - - [05/Sep/2025 10:47:23] "[35m[1mSSH-2.0-Go[0m" HTTPStatus.BAD_REQUEST -
196.251.83.136 - - [05/Sep/2025 10:50:30] code 400, message Bad request syntax ('\x05\x02\x00\x02')
196.251.83.136 - - [05/Sep/2025 10:50:30] "[35m[1m\x05\x02\x00\x02[0m" HTTPStatus.BAD_REQUEST -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 11:03:27] "[35m[1mPOST /open_question HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 45, in produe_open_question_ans
    res = get_open_question_summary(request.json)
  File "/root/code/ai_based_education/main.py", line 48, in get_open_question_summary
    dim = eval_result[0]['question_section_name']
KeyError: 'question_section_name'
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 11:04:27] "[35m[1mPOST /open_question HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 45, in produe_open_question_ans
    res = get_open_question_summary(request.json)
  File "/root/code/ai_based_education/main.py", line 48, in get_open_question_summary
    dim = eval_result[0]['question_section_name']
KeyError: 'question_section_name'
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 11:06:13] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 11:07:32] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 11:10:55] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 11:12:42] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
120.27.154.98 - - [05/Sep/2025 11:13:37] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 11:25:53] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 11:35:27] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 11:36:38] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 11:42:55] "POST /open_question HTTP/1.1" 200 -
3.132.23.201 - - [05/Sep/2025 11:51:29] "[33mGET / HTTP/1.1[0m" 404 -
3.132.23.201 - - [05/Sep/2025 11:53:03] "[33mGET / HTTP/1.1[0m" 404 -
3.132.23.201 - - [05/Sep/2025 11:54:37] code 400, message Bad request version ('√Ä\x14√Ä')
3.132.23.201 - - [05/Sep/2025 11:54:37] "[35m[1m\x16\x03\x01\x00{\x01\x00\x00w\x03\x03\x92√¶/U~t\x82√ø t!q√µ¬•rJ*¬≠FR\x15√≠v√°`5¬°6i\x18l√æ\x00\x00\x1a√Ä/√Ä+√Ä\x11√Ä\x07√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
3.132.23.201 - - [05/Sep/2025 11:55:43] code 400, message Bad request syntax ('SSH-2.0-Go')
3.132.23.201 - - [05/Sep/2025 11:55:43] "[35m[1mSSH-2.0-Go[0m" HTTPStatus.BAD_REQUEST -
3.132.23.201 - - [05/Sep/2025 11:56:26] code 400, message Bad request version ('√Ä\x14√Ä')
3.132.23.201 - - [05/Sep/2025 11:56:26] "[35m[1m\x16\x03\x01\x00{\x01\x00\x00w\x03\x03√æ\x83\x147√É,?¬∫√µ¬ø\\\x0b\x06√Ö-\x18w√è6\x98¬∞¬®√≠√£M√å¬°a¬£¬ª)H\x00\x00\x1a√Ä/√Ä+√Ä\x11√Ä\x07√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
35.203.211.197 - - [05/Sep/2025 12:10:02] code 400, message Bad request version ('√Ä\x13√Ä')
35.203.211.197 - - [05/Sep/2025 12:10:02] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03√úe√øDw\x9c%XA]c¬´\x88&\x05\x08\x14f√¢Fb¬¢f\x18E√°A¬™!√µ\x12√ô √ø√Å\x85\x99\x8a√ó√Ø¬©√∑√∞k√ï@√£0¬≠!¬Æ¬©¬πz3lr¬ß\x07\x14√Ω\x8e<√ëx\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
35.203.211.197 - - [05/Sep/2025 12:10:02] code 400, message Bad request version ('√Ä(√Ä$√Ä\x14√Ä')
35.203.211.197 - - [05/Sep/2025 12:10:02] "[35m[1m\x16\x03\x01\x00√ä\x01\x00\x00√Ü\x03\x03 √Ä¬Æ¬π\x95√¶√ñ\x17lO√ä7\x08G√ú¬™√Ä√úw¬¶√Å\x82a√Ç\x09\x84\x84√®WU\x90\x8f\x00\x00h√å\x14√å\x13√Ä/√Ä+√Ä0√Ä,√Ä\x11√Ä\x07√Ä'√Ä#√Ä\x13√Ä\x09√Ä(√Ä$√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
64.62.156.222 - - [05/Sep/2025 13:09:39] "[33mGET / HTTP/1.1[0m" 404 -
64.62.156.222 - - [05/Sep/2025 13:09:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 13:53:10] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 13:54:28] "POST /open_question HTTP/1.1" 200 -
96.126.104.20 - - [05/Sep/2025 14:03:56] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [05/Sep/2025 14:03:56] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03W¬±a\\j1√¨¬•w\x06n\x09√ù\x84^E√ù√æ¬ßq√ª√ß√ò1{,q\x07¬¢√ëH√í √ß√Å√Æ\x06\x8c\x10[√π√Ç\\=K\x0f√è\x9a√æ¬£5\x8f√à¬≤>"¬øjEc\x9d\x83\x1e=¬£\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 14:03:56] "[33mGET /signin HTTP/1.1[0m" 404 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:06:19] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:06:49] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:09:09] "POST /open_question HTTP/1.1" 200 -
213.209.143.117 - - [05/Sep/2025 14:11:14] code 400, message Bad request syntax ('\x05\x02\x00\x02')
213.209.143.117 - - [05/Sep/2025 14:11:14] "[35m[1m\x05\x02\x00\x02[0m" HTTPStatus.BAD_REQUEST -
178.159.37.112 - - [05/Sep/2025 14:13:58] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*√†\x00\x00\x00\x00\x00Cookie:')
178.159.37.112 - - [05/Sep/2025 14:13:58] "[35m[1m\x03\x00\x00/*√†\x00\x00\x00\x00\x00Cookie: mstshash=Administr[0m" HTTPStatus.BAD_REQUEST -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:15:03] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:17:29] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:18:21] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:18:57] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
111.9.62.28 - - [05/Sep/2025 14:19:29] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 14:26:51] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 14:27:10] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 14:27:44] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 14:28:24] "POST /open_question HTTP/1.1" 200 -
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 668, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 373, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()
  File "/usr/lib64/python3.8/http/server.py", line 435, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.8/http/server.py", line 423, in handle_one_request
    method()
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
  File "/usr/local/lib64/python3.8/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/root/code/ai_based_education/run_app.py", line 42, in produe_open_question_ans
    logger.info('input req type:', type(request.json))
Message: 'input req type:'
Arguments: (<class 'dict'>,)
223.85.219.47 - - [05/Sep/2025 14:29:07] "POST /open_question HTTP/1.1" 200 -
205.210.31.91 - - [05/Sep/2025 15:28:35] "[33mGET / HTTP/1.0[0m" 404 -
165.154.152.6 - - [05/Sep/2025 16:48:45] "[33mGET / HTTP/1.1[0m" 404 -
165.154.152.6 - - [05/Sep/2025 16:48:45] code 400, message Bad request version ('√Ä\x13√Ä')
165.154.152.6 - - [05/Sep/2025 16:48:45] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03√í¬ß√†√Çc√éY{\x91√í-]√åf`~\x95\x9d√Ç¬¨\x92<¬™\x90Z¬ªp/√¨n√üL ¬Æ√çx\x15F\x15\x09C√æ¬≠¬∞√éz√Ñ'\x1e\x157{\x09¬©√åP{KJ\x13¬±|√ç√æ√∂\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
165.154.152.6 - - [05/Sep/2025 16:48:46] code 400, message Bad request syntax ('\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03¬Æ√Æ\x01\x954z√í:√Øm\x133&w\x82S√ª\x17\x14?√ºh(\x9c√∑¬Ω\x08√ä\x15n')
165.154.152.6 - - [05/Sep/2025 16:48:46] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03¬Æ√Æ\x01\x954z√í:√Øm\x133&w\x82S√ª\x17\x14?√ºh(\x9c√∑¬Ω\x08√ä\x15n[0m" HTTPStatus.BAD_REQUEST -
165.154.152.6 - - [05/Sep/2025 16:48:54] code 400, message Bad request syntax ('{\x01\x00\x1613911111112√Ä¬®\x01\x01\x13\x90{')
165.154.152.6 - - [05/Sep/2025 16:48:54] "[35m[1m{\x01\x00\x1613911111112√Ä¬®\x01\x01\x13\x90{[0m" HTTPStatus.BAD_REQUEST -
165.154.152.6 - - [05/Sep/2025 16:48:55] "[33mGET / HTTP/1.0[0m" 404 -
165.154.152.6 - - [05/Sep/2025 16:49:04] code 400, message Bad request syntax ('~\x00\x02\x00\x00\x02\x00\x00\x00\x00\x15\x00\x032~')
165.154.152.6 - - [05/Sep/2025 16:49:04] "[35m[1m~\x00\x02\x00\x00\x02\x00\x00\x00\x00\x15\x00\x032~[0m" HTTPStatus.BAD_REQUEST -
165.154.152.6 - - [05/Sep/2025 16:49:12] code 400, message Bad request syntax ('\x80√ï\x00\x00\x00\x05\x00+\x0e\x01\x00')
165.154.152.6 - - [05/Sep/2025 16:49:12] "[35m[1m\x80√ï\x00\x00\x00\x05\x00+\x0e\x01\x00[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 18:03:52] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [05/Sep/2025 18:03:52] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03¬¥+√óo√≥\x1et¬±[\x02√∏\x00\x80u¬æ\x05¬∞√∫n¬∞√π¬¢¬∏{$J\x98¬Ω\x0e¬Ω¬∫√Ø ¬´x\\¬∫`\x93¬Ø√ñ¬∂¬Ø)j\x8d√†I\x07t¬∏;h(lw\x1d\x93\x97\x9d¬ª{√â}?\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 18:03:52] "[33mGET /signin HTTP/1.1[0m" 404 -
138.68.156.214 - - [05/Sep/2025 21:24:34] code 400, message Bad request version ('√Ä\x14√Ä')
138.68.156.214 - - [05/Sep/2025 21:24:34] "[35m[1m\x16\x03\x01\x00{\x01\x00\x00w\x03\x03√û\x9bX\x04O\x80¬ªjDu√§¬µ\x84√∞¬ØaO¬†\x98\x82\x0el¬´\\\x1a√ò;~¬†qQ.\x00\x00\x1a√Ä/√Ä+√Ä\x11√Ä\x07√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
138.68.156.214 - - [05/Sep/2025 21:24:35] code 400, message Bad request syntax ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x033ou√•\x83\x93RHv\x10EX~√∞T')
138.68.156.214 - - [05/Sep/2025 21:24:35] "[35m[1m\x16\x03\x01\x00{\x01\x00\x00w\x03\x033ou√•\x83\x93RHv\x10EX~√∞T[0m" HTTPStatus.BAD_REQUEST -
138.68.156.214 - - [05/Sep/2025 21:24:35] "[33mGET / HTTP/1.1[0m" 404 -
167.94.138.113 - - [05/Sep/2025 22:01:26] code 400, message Bad request version ('√Ä\x14√Ä')
167.94.138.113 - - [05/Sep/2025 22:01:26] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03\x1d¬Æ$√£√£m\x1a¬¥C¬≥C√≠¬∂¬¨¬¨\x11√ì\x8eZ.¬æ5Q\x09\x97q1h%\x0c√∫s \x00\x14#√±qp!√ç¬•¬∑√ôP\x9f√∑4√öi√≠\x80/¬∏40,√æb√ó√®L\x09√•K\x00&√å¬®√å¬©√Ä/√Ä0√Ä+√Ä,√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
167.94.138.113 - - [05/Sep/2025 22:01:27] "[33mGET / HTTP/1.1[0m" 404 -
96.126.104.20 - - [05/Sep/2025 22:02:05] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [05/Sep/2025 22:02:05] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03\x1d5√∂2¬Ω\x07%U7>?o\x8f√±{ \x9cYL\x92√ç;g\x8f¬∑\x04¬ß¬¢\x96√∫2√ï √ø¬∞ls¬Æ√ª\x03¬∏√¶^(EK\x19V√ñ^Nyyq\x16]n¬§\x8d¬∂¬µ\x06\x8dy#\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [05/Sep/2025 22:02:06] "[33mGET /signin HTTP/1.1[0m" 404 -
20.40.250.19 - - [05/Sep/2025 22:19:16] "[33mGET /v2/ HTTP/1.1[0m" 404 -
123.160.221.141 - - [05/Sep/2025 22:47:50] code 400, message Bad request version ('√Ä\x13√Ä')
123.160.221.141 - - [05/Sep/2025 22:47:50] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03I\x06¬≤√π¬º\x99i√ÄY√ª√∏¬∫e-\x83Ud]\x0e\x8d¬∑b8¬¥g√Ü√ù9dZ8f g√Å\x81i¬≥√∂√≤√ã¬∞¬©\x19N√ñ¬Ω\x95g|p√º√©<Z¬°\x90T¬∑√©¬•8'O;\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
123.160.221.141 - - [05/Sep/2025 22:48:00] "[33mGET / HTTP/1.1[0m" 404 -
196.251.69.18 - - [06/Sep/2025 01:24:52] code 400, message Bad request syntax ('\x05\x02\x00\x02')
196.251.69.18 - - [06/Sep/2025 01:24:52] "[35m[1m\x05\x02\x00\x02[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 01:54:42] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [06/Sep/2025 01:54:42] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03√®N\x9c>√ª\x96√è\x11+¬°]Z\x96¬∑√Åaimz√π√π√¶zn¬µp\x84¬©\x8d{√©√π 'u4√ü√õM\x98√§"\x80`m√É¬¨√íDmyE¬™D√è√´√´¬™j√∑¬†\x156+\x1b\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 01:54:43] "[33mGET /signin HTTP/1.1[0m" 404 -
198.235.24.130 - - [06/Sep/2025 02:10:05] "[33mGET / HTTP/1.1[0m" 404 -
45.156.128.156 - - [06/Sep/2025 05:06:37] "[33mGET / HTTP/1.1[0m" 404 -
45.156.128.156 - - [06/Sep/2025 05:07:00] "[33mGET /cgi-bin/authLogin.cgi HTTP/1.1[0m" 404 -
45.156.128.158 - - [06/Sep/2025 05:07:16] "[33mGET /api/session/properties HTTP/1.1[0m" 404 -
96.126.104.20 - - [06/Sep/2025 05:54:28] code 400, message Bad request version ('Gljm')
96.126.104.20 - - [06/Sep/2025 05:54:28] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03Flg6E¬π√†√∂N√±z\x80w√´"¬†√æ√Ω\x7f√¨)√ú#¬¨¬∞\x07\x94WI\x13\x82¬± \x1cGljm[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 05:54:29] "[33mGET /signin HTTP/1.1[0m" 404 -
35.203.211.181 - - [06/Sep/2025 05:59:55] code 400, message Bad request syntax ('\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03√¶#Z¬Æw%s\x83')
35.203.211.181 - - [06/Sep/2025 05:59:55] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03√¶#Z¬Æw%s\x83[0m" HTTPStatus.BAD_REQUEST -
35.203.211.181 - - [06/Sep/2025 05:59:55] code 400, message Bad request version ('√Ä(√Ä$√Ä\x14√Ä')
35.203.211.181 - - [06/Sep/2025 05:59:55] "[35m[1m\x16\x03\x01\x00√ä\x01\x00\x00√Ü\x03\x03Z"\x8f\x88M√©q6√ö\x95~\x02√ó√å\x14\x11√î\x91s¬™\x09c\x88√õ]√¨¬•\x95\x0b√ø¬Æ@\x00\x00h√å\x14√å\x13√Ä/√Ä+√Ä0√Ä,√Ä\x11√Ä\x07√Ä'√Ä#√Ä\x13√Ä\x09√Ä(√Ä$√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
167.94.145.101 - - [06/Sep/2025 06:28:25] code 400, message Bad request version ('√Ä\x14√Ä')
167.94.145.101 - - [06/Sep/2025 06:28:25] "[35m[1m\x16\x03\x01\x00√Æ\x01\x00\x00√™\x03\x03√ÖY√ùUD√†9√ào√†¬®\x9e√°\x98¬≥√±\x01[\x17√á\x88t[√Ñ\x1b¬™√àJ√ï√å¬∫¬® \x0bd*¬æN¬£X√øg√û\x18\x88¬´√Ç√©\x14}`h\x8eg¬≤\x87Wx=7\x9d\x84y0¬•\x00&√å¬®√å¬©√Ä/√Ä0√Ä+√Ä,√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
167.94.145.101 - - [06/Sep/2025 06:28:29] "[33mGET / HTTP/1.1[0m" 404 -
167.94.145.101 - - [06/Sep/2025 06:28:33] "[33mGET / HTTP/1.1[0m" 404 -
167.94.145.101 - - [06/Sep/2025 06:28:33] code 505, message Invalid HTTP version (2.0)
167.94.145.101 - - [06/Sep/2025 06:28:33] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
167.94.145.101 - - [06/Sep/2025 06:28:39] code 505, message Invalid HTTP version (2.0)
167.94.145.101 - - [06/Sep/2025 06:28:39] "[35m[1mPRI * HTTP/2.0[0m" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
167.94.145.101 - - [06/Sep/2025 06:28:39] "[33mGET /sitemap.xml HTTP/1.1[0m" 404 -
101.133.136.80 - - [06/Sep/2025 08:10:46] "[33mGET / HTTP/1.0[0m" 404 -
101.133.136.80 - - [06/Sep/2025 08:10:53] code 400, message Bad request version ('RTSP/1.0')
101.133.136.80 - - [06/Sep/2025 08:10:53] "[35m[1mOPTIONS / RTSP/1.0[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:05] code 400, message Bad HTTP/0.9 request type ('\x00')
101.133.136.80 - - [06/Sep/2025 08:11:05] "[35m[1m\x00\x1e\x00\x06\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07version\x04bind\x00\x00\x10\x00\x03[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:12] code 400, message Bad request version ('0.12\x00')
101.133.136.80 - - [06/Sep/2025 08:11:12] "[35m[1m\x00\x00\x00¬§√øSMBr\x00\x00\x00\x00\x08\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x06\x00\x00\x01\x00\x00\x81\x00\x02PC NETWORK PROGRAM 1.0\x00\x02MICROSOFT NETWORKS 1.03\x00\x02MICROSOFT NETWORKS 3.0\x00\x02LANMAN1.0\x00\x02LM1.2X002\x00\x02Samba\x00\x02NT LANMAN 1.0\x00\x02NT LM 0.12\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:19] code 400, message Bad request version ('GetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00')
101.133.136.80 - - [06/Sep/2025 08:11:19] "[35m[1m\x00\x00\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x0cGetClassName\x00\x00\x00\x02\x04\x00\x00\x00\x00\x01\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:21] "[33mOPTIONS / HTTP/1.0[0m" 404 -
101.133.136.80 - - [06/Sep/2025 08:11:31] code 400, message Bad request version ('\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:11:31] "[35m[1m\x80\x00\x00(r√æ\x1d\x13\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86¬†\x00\x01\x97|\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:38] code 400, message Bad HTTP/0.9 request type ('\x00')
101.133.136.80 - - [06/Sep/2025 08:11:38] "[35m[1m\x00\x0c\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:40] code 400, message Bad request syntax ('EHLO')
101.133.136.80 - - [06/Sep/2025 08:11:40] "[35m[1mEHLO[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:45] code 400, message Bad request syntax ('HELP')
101.133.136.80 - - [06/Sep/2025 08:11:45] "[35m[1mHELP[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:51] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G√ó√∑¬∫,√Æ√™¬≤`~√≥\x00√Ω\x82{¬π√ï\x96√àw\x9b√¶√Ñ√õ<=√õo√Ø\x10n\x00\x00(\x00\x16\x00\x13\x00')
101.133.136.80 - - [06/Sep/2025 08:11:51] "[35m[1m\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G√ó√∑¬∫,√Æ√™¬≤`~√≥\x00√Ω\x82{¬π√ï\x96√àw\x9b√¶√Ñ√õ<=√õo√Ø\x10n\x00\x00(\x00\x16\x00\x13\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:11:56] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%√†\x00\x00\x00\x00\x00Cookie:')
101.133.136.80 - - [06/Sep/2025 08:11:56] "[35m[1m\x03\x00\x00*%√†\x00\x00\x00\x00\x00Cookie: mstshash=nmap[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:01] code 400, message Bad request version ('\x00/\x00')
101.133.136.80 - - [06/Sep/2025 08:12:01] "[35m[1m\x16\x03\x00\x00i\x01\x00\x00e\x03\x03U\x1c¬ß√§random1random2random3random4\x00\x00\x0c\x00/\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:08] code 400, message Bad HTTP/0.9 request type ('\x80\x9e\x01\x03\x01\x00u\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:12:08] "[35m[1m\x80\x9e\x01\x03\x01\x00u\x00\x00\x00 \x00\x00f\x00\x00e\x00\x00d\x00\x00c\x00\x00b\x00\x00:\x00\x009\x00\x008\x00\x005\x00\x004\x00\x003\x00\x002\x00\x00/\x00\x00\x1b\x00\x00\x1a\x00\x00\x19\x00\x00\x18\x00\x00\x17\x00\x00\x16\x00\x00\x15\x00\x00\x14\x00\x00\x13\x00\x00\x12\x00\x00\x11\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:14] code 400, message Bad request syntax ('\x00\x00\x00qj\x81n0\x81k¬°\x03\x02\x01\x05¬¢\x03\x02\x01')
101.133.136.80 - - [06/Sep/2025 08:12:14] "[35m[1m\x00\x00\x00qj\x81n0\x81k¬°\x03\x02\x01\x05¬¢\x03\x02\x01[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:25] code 400, message Bad HTTP/0.9 request type ('l\x00')
101.133.136.80 - - [06/Sep/2025 08:12:25] "[35m[1ml\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:27] "[33mGET /nice%20ports,/Trinity.txt.bak HTTP/1.0[0m" 404 -
101.133.136.80 - - [06/Sep/2025 08:12:32] code 400, message Bad request syntax ('\x01default')
101.133.136.80 - - [06/Sep/2025 08:12:32] "[35m[1m\x01default[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:39] code 400, message Bad request syntax ('0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00')
101.133.136.80 - - [06/Sep/2025 08:12:39] "[35m[1m0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:51] code 400, message Bad HTTP/0.9 request type ('0')
101.133.136.80 - - [06/Sep/2025 08:12:51] "[35m[1m0\x0c\x02\x01\x01`\x07\x02\x01\x02\x04\x00\x80\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:12:53] code 400, message Bad request version ('SIP/2.0')
101.133.136.80 - - [06/Sep/2025 08:12:53] "[35m[1mOPTIONS sip:nm SIP/2.0[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:04] code 400, message Bad request syntax ('TNMP\x04\x00\x00\x00TNME\x00\x00\x04\x00')
101.133.136.80 - - [06/Sep/2025 08:13:04] "[35m[1mTNMP\x04\x00\x00\x00TNME\x00\x00\x04\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:12] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:13:12] "[35m[1m\x03\x00\x00\x0b\x06√†\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:19] code 400, message Bad request syntax ('DmdT\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\x00\x11\x11\x00√ø\x01√ø\x13')
101.133.136.80 - - [06/Sep/2025 08:13:19] "[35m[1mDmdT\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\x00\x11\x11\x00√ø\x01√ø\x13[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:25] code 400, message Bad HTTP/0.9 request type (':\x00\x00\x00/\x00\x00\x00\x02\x00\x00@\x02\x0f\x00\x01\x00=\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00@')
101.133.136.80 - - [06/Sep/2025 08:13:25] "[35m[1m:\x00\x00\x00/\x00\x00\x00\x02\x00\x00@\x02\x0f\x00\x01\x00=\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:32] code 400, message Bad request syntax ('DIST00000001ARGC00000005ARGV00000002ccARGV00000002-cARGV00000006nmap.cARGV00000002-oARGV00000006nmap.oDOTI00000000')
101.133.136.80 - - [06/Sep/2025 08:13:32] "[35m[1mDIST00000001ARGC00000005ARGV00000002ccARGV00000002-cARGV00000006nmap.cARGV00000002-oARGV00000006nmap.oDOTI00000000[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:39] code 400, message Bad request syntax ('JRMI\x00\x02K')
101.133.136.80 - - [06/Sep/2025 08:13:39] "[35m[1mJRMI\x00\x02K[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:46] code 400, message Bad request syntax ('\x01\x00\x00\x00\x01\x00\x00\x00\x08\x08')
101.133.136.80 - - [06/Sep/2025 08:13:46] "[35m[1m\x01\x00\x00\x00\x01\x00\x00\x00\x08\x08[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:47] code 400, message Bad request version ('>')
101.133.136.80 - - [06/Sep/2025 08:13:47] "[35m[1m< NTP/1.0 >[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:13:57] code 400, message Bad request version ('\x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00√†m√ü_')
101.133.136.80 - - [06/Sep/2025 08:13:57] "[35m[1m\x01\x00\x00√Ω√é√∫\x0b¬∞¬†\x00\x00\x00MMS\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x03\x00√∞√∞√∞√∞\x0b\x00\x04\x00\x1c\x00\x03\x00N\x00S\x00P\x00l\x00a\x00y\x00e\x00r\x00/\x009\x00.\x000\x00.\x000\x00.\x002\x009\x008\x000\x00;\x00 \x00{\x000\x000\x000\x000\x00A\x00A\x000\x000\x00-\x000\x00A\x000\x000\x00-\x000\x000\x00a\x000\x00-\x00A\x00A\x000\x00A\x00-\x000\x000\x000\x000\x00A\x000\x00A\x00A\x000\x00A\x00A\x000\x00}\x00\x00\x00√†m√ü_[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:04] code 400, message Bad HTTP/0.9 request type ('\x00Z\x00\x00\x01\x00\x00\x00\x016\x01,\x00\x00\x08\x00\x7f√ø\x7f\x08\x00\x00\x00\x01\x00')
101.133.136.80 - - [06/Sep/2025 08:14:04] "[35m[1m\x00Z\x00\x00\x01\x00\x00\x00\x016\x01,\x00\x00\x08\x00\x7f√ø\x7f\x08\x00\x00\x00\x01\x00 \x00:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004√¶\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00(CONNECT_DATA=(COMMAND=version))[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:06] code 400, message Bad request syntax ('Subscribe')
101.133.136.80 - - [06/Sep/2025 08:14:06] "[35m[1mSubscribe[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:11] code 400, message Bad request syntax ('Query')
101.133.136.80 - - [06/Sep/2025 08:14:11] "[35m[1mQuery[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:17] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
101.133.136.80 - - [06/Sep/2025 08:14:17] "[35m[1m\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:26] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
101.133.136.80 - - [06/Sep/2025 08:14:26] "[35m[1m\x04\x01\x00\x16\x7f\x00\x00\x01root\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:33] code 400, message Bad request version ('\x03\x00(\x00\x04√ø\x08\x00\x01U\x00\x00\x00MSSQLServer\x00H\x0f\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:14:33] "[35m[1m\x12\x01\x004\x00\x00\x00\x00\x00\x00\x15\x00\x06\x01\x00\x1b\x00\x01\x02\x00\x1c\x00\x0c\x03\x00(\x00\x04√ø\x08\x00\x01U\x00\x00\x00MSSQLServer\x00H\x0f\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:35] code 400, message Bad request syntax ('HELP')
101.133.136.80 - - [06/Sep/2025 08:14:35] "[35m[1mHELP[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:41] code 400, message Bad request syntax ('stats')
101.133.136.80 - - [06/Sep/2025 08:14:41] "[35m[1mstats[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:45] code 400, message Bad request version ('\x06\x00\x00\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:14:45] "[35m[1m\x00\x00\x00\x01\x00\x00\x00\x13\x00\x00\x00\x02\x00\x00\x00$\x00\x00\x00\x0bservice_mgr\x00\x00\x00\x00\x02\x00\x00\x00\x13\x01\x08scanner \x04\x05nmap \x06\x00\x00\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:14:57] code 400, message Bad request version ('\x00\x00\x00\x04')
101.133.136.80 - - [06/Sep/2025 08:14:57] "[35m[1m\x00\x00\x00\x00DB2DAS      \x01\x04\x00\x00\x00\x109z\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x0c\x00\x00\x00\x00\x00\x00\x0c\x00\x00\x00\x0c\x00\x00\x00\x04[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:05] code 400, message Bad request version ('\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00√ø\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00√§\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f')
101.133.136.80 - - [06/Sep/2025 08:15:05] "[35m[1m\x01√Ç\x00\x00\x00\x04\x00\x00¬∂\x01\x00\x00SQLDB2RA\x00\x01\x00\x00\x04\x01\x01\x00\x05\x00\x1d\x00\x88\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x08\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x01\x00\x00@\x00\x00\x00@\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x02\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x00\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x00\x04\x00\x00\x00\x04\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x03\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00\x80\x00\x00\x00\x01\x08\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x10\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x10\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x04\x00\x00@\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x09\x00\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x04\x00\x00\x00\x03\x00\x00\x80\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x04\x00\x00\x01\x00\x00\x80\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x01\x00\x00\x00\x00\x01\x00\x00@\x00\x00\x00\x00        \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00√ø\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00√§\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x7f[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:11] code 400, message Bad request version ('1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:15:11] "[35m[1mClient string for PARC version 1 Wire Encryption version 1\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:13] code 400, message Bad HTTP/0.9 request type ('<\x00K\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:15:13] "[35m[1m<\x00K\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00√ø√ø√ø√ø\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:17] code 400, message Bad request syntax ('\x124\x00\x01')
101.133.136.80 - - [06/Sep/2025 08:15:17] "[35m[1m\x124\x00\x01[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:27] code 400, message Bad request syntax ('\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x0f\x00')
101.133.136.80 - - [06/Sep/2025 08:15:27] "[35m[1m\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x0f\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:28] code 400, message Bad request syntax ('serverstatus')
101.133.136.80 - - [06/Sep/2025 08:15:28] "[35m[1mserverstatus[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:39] code 400, message Bad HTTP/0.9 request type ('√Ç√•√•√•\x9e')
101.133.136.80 - - [06/Sep/2025 08:15:39] "[35m[1m√Ç√•√•√•\x9e¬†√ó¬§¬¶√ê√ï√ù√ú√à√ñ√ù√ó√ï√à√ë√ñ\x83\x80√à√ù¬§√ë¬°√à¬§√í√ï√ó√ù¬£¬§¬°√ù¬¶√ó√ù\x98√•[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:40] code 400, message Bad request syntax ('#ST')
101.133.136.80 - - [06/Sep/2025 08:15:40] "[35m[1m#ST[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:50] code 400, message Bad request version ('\x00\x00\x00\x03\x00\x05nmap\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\x00\x00\x00\x7f')
101.133.136.80 - - [06/Sep/2025 08:15:50] "[35m[1m\x00\x94\x01<\x00\x00\x00d\x00e\x00\x00\x00=\x00\x06IEEEM\x00\x00lsqlexec\x00\x00\x00\x00\x00\x00\x069.280\x00\x00\x0cRDS#R000000\x00\x00\x05sqli\x00\x00\x00\x013\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x05nmap\x00\x00\x05nmap\x00ol\x00\x00\x00\x00\x00\x00\x00\x00\x00=tlitcp\x00\x00\x00\x00\x00\x01\x00h\x00\x0b\x00\x00\x00\x03\x00\x05nmap\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00j\x00\x00\x00\x7f[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:15:59] code 400, message Bad request syntax ('\x002√ê\x01\x00\x01\x00,\x10A\x00\x04\x11^\x00\x04\x11m\x00\x04\x11Z\x00\x18\x14\x04\x14\x03\x00\x07$\x07\x00\x08$\x0f\x00\x08\x14@\x00\x08\x14t\x00\x08\x00\x04\x11G')
101.133.136.80 - - [06/Sep/2025 08:15:59] "[35m[1m\x002√ê\x01\x00\x01\x00,\x10A\x00\x04\x11^\x00\x04\x11m\x00\x04\x11Z\x00\x18\x14\x04\x14\x03\x00\x07$\x07\x00\x08$\x0f\x00\x08\x14@\x00\x08\x14t\x00\x08\x00\x04\x11G[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:00] code 400, message Bad HTTP/0.9 request type ('TSH')
101.133.136.80 - - [06/Sep/2025 08:16:00] "[35m[1mTSH \x00\x00\x00√¨\x01\x011\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x11\x04¬∏\x00\x00ID  [0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:05] "[33mGET /server-info HTTP/1.1[0m" 404 -
101.133.136.80 - - [06/Sep/2025 08:16:14] code 400, message Bad request syntax ('A\x00\x00\x00:0\x00\x00√ø√ø√ø√ø√î\x07\x00\x00\x00\x00\x00\x00test.$cmd\x00\x00\x00\x00\x00√ø√ø√ø√ø\x1b\x00\x00\x00\x01serverStatus\x00\x00\x00\x00\x00\x00\x00√∞?\x00')
101.133.136.80 - - [06/Sep/2025 08:16:14] "[35m[1mA\x00\x00\x00:0\x00\x00√ø√ø√ø√ø√î\x07\x00\x00\x00\x00\x00\x00test.$cmd\x00\x00\x00\x00\x00√ø√ø√ø√ø\x1b\x00\x00\x00\x01serverStatus\x00\x00\x00\x00\x00\x00\x00√∞?\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:16] code 400, message Bad request syntax ('*1')
101.133.136.80 - - [06/Sep/2025 08:16:16] "[35m[1m*1[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:26] code 400, message Bad request syntax ('\x00\x00\x00\x01\x07')
101.133.136.80 - - [06/Sep/2025 08:16:26] "[35m[1m\x00\x00\x00\x01\x07[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:27] code 400, message Bad HTTP/0.9 request type ('show')
101.133.136.80 - - [06/Sep/2025 08:16:27] "[35m[1mshow info[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:37] code 400, message Bad request syntax ('\x80\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15√∞√ëb\x00\x00\x00\x00\x00\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:16:37] "[35m[1m\x80\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15√∞√ëb\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:44] code 400, message Bad request syntax ('\x00\x01n')
101.133.136.80 - - [06/Sep/2025 08:16:44] "[35m[1m\x00\x01n[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:50] code 400, message Bad request syntax ('vp3')
101.133.136.80 - - [06/Sep/2025 08:16:50] "[35m[1mvp3[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:16:55] code 400, message Bad request syntax ('\x94\x00√ç√Ø√ëa\x91\x03')
101.133.136.80 - - [06/Sep/2025 08:16:55] "[35m[1m\x94\x00√ç√Ø√ëa\x91\x03[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:02] code 400, message Bad request syntax ('√æ\x01')
101.133.136.80 - - [06/Sep/2025 08:17:02] "[35m[1m√æ\x01[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:03] "[33mGET /version HTTP/1.1[0m" 404 -
101.133.136.80 - - [06/Sep/2025 08:17:12] code 400, message Bad request syntax ('\x00\x00\x07\x00\x08\x00\x03\x00\x04\x00\x05\x00\x06')
101.133.136.80 - - [06/Sep/2025 08:17:12] "[35m[1m\x00\x00\x07\x00\x08\x00\x03\x00\x04\x00\x05\x00\x06[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:18] code 400, message Bad request syntax ('√ø√ª\x18√ø√∫\x18\x00IBM-3279-4-E√ø√∞√ø√ª\x19√ø√Ω\x19√ø√ª\x00√ø√Ω\x00')
101.133.136.80 - - [06/Sep/2025 08:17:18] "[35m[1m√ø√ª\x18√ø√∫\x18\x00IBM-3279-4-E√ø√∞√ø√ª\x19√ø√Ω\x19√ø√ª\x00√ø√Ω\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:23] code 400, message Bad request syntax ('GIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:17:23] "[35m[1mGIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:29] code 400, message Bad request syntax ('VERSION')
101.133.136.80 - - [06/Sep/2025 08:17:29] "[35m[1mVERSION[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:34] code 400, message Bad request syntax ('CNXN\x00\x00\x00\x01\x00\x10\x00\x00\x07\x00\x00\x002\x02\x00\x00¬º¬±¬ß¬±host::\x00')
101.133.136.80 - - [06/Sep/2025 08:17:34] "[35m[1mCNXN\x00\x00\x00\x01\x00\x10\x00\x00\x07\x00\x00\x002\x02\x00\x00¬º¬±¬ß¬±host::\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:40] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00\x10\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:17:40] "[35m[1m\x00\x00\x00\x10\x00\x00\x00\x0c{"code":106}[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:45] code 400, message Bad request syntax ('\x0c\x00\x01\x00\x00\x00ImYorDad0u\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:17:45] "[35m[1m\x0c\x00\x01\x00\x00\x00ImYorDad0u\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:17:50] code 400, message Bad HTTP/0.9 request type ('√ö√ö\x01\x00\x00\x00\x14\x00\x10\x03\x08\x00\x00\x00')
101.133.136.80 - - [06/Sep/2025 08:17:50] "[35m[1m√ö√ö\x01\x00\x00\x00\x14\x00\x10\x03\x08\x00\x00\x00\x0bM\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:20:35] code 400, message Bad request version ("¬∫l\x98\x1bj√§\x8c\x94\x8c√≥0¬™√î√§\x07√∂\x94\x08\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/√Ä,√Ä0\x00¬£\x00\x9f√å¬©√å¬®√å¬™√Ä¬Ø√Ä\xad√Ä¬£√Ä\x9f√Ä]√Äa√ÄW√ÄS√Ä+√Ä/\x00¬¢\x00\x9e√Ä¬Æ√Ä¬¨√Ä¬¢√Ä\x9e√Ä\\√Ä`√ÄV√ÄR√Ä$√Ä(\x00k\x00j√Äs√Äw\x00√Ñ\x00√É√Ä#√Ä'\x00g\x00@√Är√Äv\x00¬æ\x00¬Ω√Ä")
101.133.136.80 - - [06/Sep/2025 08:20:35] "[35m[1m\x16\x03\x01\x02\x00\x01\x00\x01√º\x03\x03L\x98\x09¬¥√øN√ü√É√ùAu√Ω\x08'√ç¬≤\x8d¬Ω\x15√á¬©!√ü3√ók\x04\x1dA\x14bN √Öj\x04√≥¬∂b√æNx√á¬∂¬∏S\x1d¬∫l\x98\x1bj√§\x8c\x94\x8c√≥0¬™√î√§\x07√∂\x94\x08\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/√Ä,√Ä0\x00¬£\x00\x9f√å¬©√å¬®√å¬™√Ä¬Ø√Ä¬≠√Ä¬£√Ä\x9f√Ä]√Äa√ÄW√ÄS√Ä+√Ä/\x00¬¢\x00\x9e√Ä¬Æ√Ä¬¨√Ä¬¢√Ä\x9e√Ä\\√Ä`√ÄV√ÄR√Ä$√Ä(\x00k\x00j√Äs√Äw\x00√Ñ\x00√É√Ä#√Ä'\x00g\x00@√Är√Äv\x00¬æ\x00¬Ω√Ä[0m" HTTPStatus.BAD_REQUEST -
101.133.136.80 - - [06/Sep/2025 08:20:53] code 400, message Bad HTTP/0.9 request type ('\x80\x00\x00(!Y√ä;\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86')
101.133.136.80 - - [06/Sep/2025 08:20:53] "[35m[1m\x80\x00\x00(!Y√ä;\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01\x86¬†\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 09:58:46] code 400, message Bad request syntax ('\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03√û_E√íP.√ò1{!\x14RI\x18_%√ï√£√ã√™l')
96.126.104.20 - - [06/Sep/2025 09:58:46] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03√û_E√íP.√ò1{!\x14RI\x18_%√ï√£√ã√™l[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 09:58:46] "[33mGET /signin HTTP/1.1[0m" 404 -
147.185.132.105 - - [06/Sep/2025 10:23:19] "[33mGET / HTTP/1.0[0m" 404 -
198.235.24.13 - - [06/Sep/2025 11:34:27] "[33mGET / HTTP/1.0[0m" 404 -
3.132.23.201 - - [06/Sep/2025 11:37:40] "[33mGET / HTTP/1.1[0m" 404 -
3.132.23.201 - - [06/Sep/2025 11:41:34] code 400, message Bad request version ('√Ä\x14√Ä')
3.132.23.201 - - [06/Sep/2025 11:41:34] "[35m[1m\x16\x03\x01\x00{\x01\x00\x00w\x03\x03¬Ø\x12-\x11√Ü/\x0c√°\x1fK\x94D√∏¬ª√ø\x1d\x99l!\x90\x9f\x93¬Ω\x1e?\x82\x154\x98\x04`\x8a\x00\x00\x1a√Ä/√Ä+√Ä\x11√Ä\x07√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
3.132.23.201 - - [06/Sep/2025 11:43:09] code 400, message Bad request syntax ('SSH-2.0-Go')
3.132.23.201 - - [06/Sep/2025 11:43:09] "[35m[1mSSH-2.0-Go[0m" HTTPStatus.BAD_REQUEST -
3.132.23.201 - - [06/Sep/2025 11:44:59] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03M\x98SF¬¢c\x10y\x8d\x82{¬≥x√ì√ø\x91\x8d¬±√ê√™2\x94¬±R~\x84\x00ce√é¬´√î\x00\x00\x1a√Ä/√Ä+√Ä\x11√Ä\x07√Ä\x13√Ä')
3.132.23.201 - - [06/Sep/2025 11:44:59] "[35m[1m\x16\x03\x01\x00{\x01\x00\x00w\x03\x03M\x98SF¬¢c\x10y\x8d\x82{¬≥x√ì√ø\x91\x8d¬±√ê√™2\x94¬±R~\x84\x00ce√é¬´√î\x00\x00\x1a√Ä/√Ä+√Ä\x11√Ä\x07√Ä\x13√Ä\x09√Ä\x14√Ä[0m" HTTPStatus.BAD_REQUEST -
65.49.1.182 - - [06/Sep/2025 13:31:24] "[33mGET / HTTP/1.1[0m" 404 -
65.49.1.182 - - [06/Sep/2025 13:31:43] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
96.126.104.20 - - [06/Sep/2025 13:57:54] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [06/Sep/2025 13:57:54] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03\x92:u\x9f\x81\x90√û\x99\x85√ár\x0d\x8c√´√è\x1d8\x9d4√º√¨¬æ\x04 ¬¨¬π√ÖP\x9a`.\x86 ¬≠Y¬æu√Ø√±8g√®qI√∂√ñ¬•√°\x9a,¬†\x04\x80gE\x0e¬∏36\x04\x1e\x80\x1c\x8e\x0d\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 13:57:54] "[33mGET /signin HTTP/1.1[0m" 404 -
142.93.230.252 - - [06/Sep/2025 14:09:42] "[33mGET / HTTP/1.1[0m" 404 -
198.235.24.113 - - [06/Sep/2025 17:35:20] "[33mGET / HTTP/1.1[0m" 404 -
96.126.104.20 - - [06/Sep/2025 17:56:14] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [06/Sep/2025 17:56:14] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03√ü8{~rc&`¬†\x0dQ√á√ø √≤√å¬¶AI\x01;o\x15√õ√îJ\x9e\x14N√∫√©\x8b O\x14$\x82\x14)√æ√ë\x7fq2√ï\x98√ãx¬≠\x84~vX>√ß¬•Y\x1eK¬´√∑p√ù\x82\x03\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 17:56:15] "[33mGET /signin HTTP/1.1[0m" 404 -
39.103.152.13 - - [06/Sep/2025 19:08:16] code 400, message Bad request version ("√∞\x9fK√Ω√ó¬ª~q\x83√¶√Ä√æ√¥√ç~¬∏√ä\x94√ΩN√â√å\x8b√å4(√¢√¢√ÖoZZ\x00>\x13\x02\x13\x03\x13\x01√Ä,√Ä0\x00\x9f√å¬©√å¬®√å¬™√Ä+√Ä/\x00\x9e√Ä$√Ä(\x00k√Ä#√Ä'\x00g√Ä")
39.103.152.13 - - [06/Sep/2025 19:08:16] "[35m[1m\x16\x03\x01\x02\x00\x01\x00\x01√º\x03\x03\x17√û√ê√ü¬ª:¬Æ0\x04√çT¬∫\x810z¬Æb¬°√≥\x0c+o√ê\x1b√Ä¬∫$\x89√ó¬º\x18H √∞\x9fK√Ω√ó¬ª~q\x83√¶√Ä√æ√¥√ç~¬∏√ä\x94√ΩN√â√å\x8b√å4(√¢√¢√ÖoZZ\x00>\x13\x02\x13\x03\x13\x01√Ä,√Ä0\x00\x9f√å¬©√å¬®√å¬™√Ä+√Ä/\x00\x9e√Ä$√Ä(\x00k√Ä#√Ä'\x00g√Ä[0m" HTTPStatus.BAD_REQUEST -
39.103.152.13 - - [06/Sep/2025 19:08:16] "[33mGET / HTTP/1.1[0m" 404 -
96.126.104.20 - - [06/Sep/2025 21:59:25] code 400, message Bad request version ('√Ä\x13√Ä')
96.126.104.20 - - [06/Sep/2025 21:59:25] "[35m[1m\x16\x03\x01\x00√≤\x01\x00\x00√Æ\x03\x03E\x87\x85[√ü¬¶√Ç√©¬±\x80\x87`Q\x10Gt√Ço~z√æxvx¬§ \x97\x0f√ΩvD> \x1d√Ø√π√ù¬°√≥¬≠\x11\x8c@√µ√ü√Ñ\x07*\x18W√î√±ew¬∏\x15\x8c,t\x81√ñ¬∫j√óC\x00&√Ä+√Ä/√Ä,√Ä0√å¬©√å¬®√Ä\x09√Ä\x13√Ä[0m" HTTPStatus.BAD_REQUEST -
96.126.104.20 - - [06/Sep/2025 21:59:25] "[33mGET /signin HTTP/1.1[0m" 404 -
 * Detected change in '/root/code/ai_based_education/main.py', reloading
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'ÈóÆÈ¢ò', 'answer': 'Á≠îÊ°à'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'ÈóÆÈ¢ò', 'answer': 'Á≠îÊ°à'}]
input_check_result: False
input_check_result: False
input_check_result: False
input_check_result: False
eval_result [{'question_type': 2, 'answer': 'ÊñπÂºèÂèëÁîµÂÖ¨Âè∏Âú∞Êñπ'}]
input_check_result: False
eval_result [{'question_type': 2, 'answer': 'ÊñπÂºèÂèëÁîµÂÖ¨Âè∏Âú∞Êñπ'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπË¥®', 'question_type': 2, 'question': 'ËØ∑ÂõûÂøÜÊúÄËøë‰∏ÄÊ¨°ÂíåÂêåÂ≠¶/ÊúãÂèãÂèëÁîü‰∏çÊÑâÂø´ÁöÑ‰∫ãÊÉÖÔºåÊèèËø∞‰∏Ä‰∏ãÁªèËøá„ÄÇÔºà40-90ÁßíÔºâ', 'answer': 'ÊñπÂºèÂèëÁîµÂÖ¨Âè∏Âú∞Êñπ'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπË¥®', 'question_type': 2, 'question': 'ËØ∑ÂõûÂøÜÊúÄËøë‰∏ÄÊ¨°ÂíåÂêåÂ≠¶/ÊúãÂèãÂèëÁîü‰∏çÊÑâÂø´ÁöÑ‰∫ãÊÉÖÔºåÊèèËø∞‰∏Ä‰∏ãÁªèËøá„ÄÇÔºà40-90ÁßíÔºâ', 'answer': 'ÊñπÂºèÂèëÁîµÂÖ¨Âè∏Âú∞Êñπ'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶‰∏öË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúÄÂñúÊ¨¢ÁöÑÂ≠¶ÁßëÊòØÂì™‰∏Ä‰∏™Ôºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢ÔºüÊúâÂèÇÂä†ËøáÂ≠¶ÁßëÁ´ûËµõÂêóÔºüÊòØ‰ªÄ‰πàÁ´ûËµõÔºüÊúâÊãøÂà∞Â•ñÈ°πÂêóÔºü', 'answer': 'ÊöÇÊó∂Ê≤°ÊúâÔºåÊ≤°ÊúâÂ•ñÈ°π'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶ËÉΩË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúâÂ§öÂ∞ë‰∏™Â≠¶ÁßëË°•‰π†Áè≠ÔºüË°•‰π†ÁöÑÂÜÖÂÆπÊòØÊ†°ÂÜÖÁõ∏ÂÖ≥ËøòÊòØÈ¢ùÂ§ñÊãìÂ±ïÔºüÊúâÊòéÊòæÊïàÊûúÂêóÔºü/ÂØπÂ≠©Â≠êÊúâÂ∏ÆÂä©ÂêóÔºü', 'answer': 'ÁßëÁõÆÔºöËØ≠Êñá\nÂØπÂ≠©Â≠êÊúâÂ∏ÆÂä©'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπÂæÅ', 'question_type': 2, 'question': 'ÈóÆÈ¢ò', 'answer': 'Á≠îÊ°à'}]
input_check_result: False
eval_result [{'question_section_name': 'ÁªºÂêàÁ¥†Ë¥®', 'question_type': 2, 'question': '‰Ω†/Â≠©Â≠êÂπ≥Êó∂ÊúÄÂñúÊ¨¢ÁöÑÊ¥ªÂä®ÊàñÂ≠¶ÁßëÊòØ‰ªÄ‰πàÔºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢Ôºü', 'answer': 'ÊòØÂèëÁîµÂÖ¨Âè∏Âú∞ÊñπÂëäËØâÂØπÊñπ'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπË¥®', 'question_type': 2, 'question': 'ËØ∑ÂõûÂøÜÊúÄËøë‰∏ÄÊ¨°ÂíåÂêåÂ≠¶/ÊúãÂèãÂèëÁîü‰∏çÊÑâÂø´ÁöÑ‰∫ãÊÉÖÔºåÊèèËø∞‰∏Ä‰∏ãÁªèËøá„ÄÇÔºà40-90ÁßíÔºâ', 'answer': 'rtyry'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶‰∏öË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúÄÂñúÊ¨¢ÁöÑÂ≠¶ÁßëÊòØÂì™‰∏Ä‰∏™Ôºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢ÔºüÊúâÂèÇÂä†ËøáÂ≠¶ÁßëÁ´ûËµõÂêóÔºüÊòØ‰ªÄ‰πàÁ´ûËµõÔºüÊúâÊãøÂà∞Â•ñÈ°πÂêóÔºü', 'answer': 'fdgsdf\n'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶ËÉΩË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúâÂ§öÂ∞ë‰∏™Â≠¶ÁßëË°•‰π†Áè≠ÔºüË°•‰π†ÁöÑÂÜÖÂÆπÊòØÊ†°ÂÜÖÁõ∏ÂÖ≥ËøòÊòØÈ¢ùÂ§ñÊãìÂ±ïÔºüÊúâÊòéÊòæÊïàÊûúÂêóÔºü/ÂØπÂ≠©Â≠êÊúâÂ∏ÆÂä©ÂêóÔºü', 'answer': 'FGDFG'}]
input_check_result: False
eval_result [{'question_section_name': 'ÁªºÂêàÁ¥†Ë¥®', 'question_type': 2, 'question': '‰Ω†/Â≠©Â≠êÂπ≥Êó∂ÊúÄÂñúÊ¨¢ÁöÑÊ¥ªÂä®ÊàñÂ≠¶ÁßëÊòØ‰ªÄ‰πàÔºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢Ôºü', 'answer': '12342234323423412346234'}]
input_check_result: False
eval_result [{'question_section_name': '‰ΩìËÇ≤Ëâ∫ÊúØ', 'question_type': 2, 'question': 'ËØ∑ÊèèËø∞‰∏Ä‰∏ãÂ≠©Â≠êËá™Â∑±ÊúÄËøë‰∏ÄÊ¨°Âú®‰ΩìËÇ≤ÊàñËâ∫ÊúØÊñπÈù¢ÂùöÊåÅÁªÉ‰π†ÊàñÂàõ‰ΩúÁöÑÁªèÂéÜÔºüÊòØ‰ªÄ‰πàËÆ©‰Ω†ÂùöÊåÅ‰∏ãÂéªÁöÑÔºü', 'answer': 'Â§ßÊííÂèëÂ∞ÑÁÇπÂèë'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπË¥®', 'question_type': 2, 'question': 'ËØ∑ÂõûÂøÜÊúÄËøë‰∏ÄÊ¨°ÂíåÂêåÂ≠¶/ÊúãÂèãÂèëÁîü‰∏çÊÑâÂø´ÁöÑ‰∫ãÊÉÖÔºåÊèèËø∞‰∏Ä‰∏ãÁªèËøá„ÄÇÔºà40-90ÁßíÔºâ', 'answer': 'rtyry'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶‰∏öË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúÄÂñúÊ¨¢ÁöÑÂ≠¶ÁßëÊòØÂì™‰∏Ä‰∏™Ôºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢ÔºüÊúâÂèÇÂä†ËøáÂ≠¶ÁßëÁ´ûËµõÂêóÔºüÊòØ‰ªÄ‰πàÁ´ûËµõÔºüÊúâÊãøÂà∞Â•ñÈ°πÂêóÔºü', 'answer': 'fdgsdf\n'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶ËÉΩË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúâÂ§öÂ∞ë‰∏™Â≠¶ÁßëË°•‰π†Áè≠ÔºüË°•‰π†ÁöÑÂÜÖÂÆπÊòØÊ†°ÂÜÖÁõ∏ÂÖ≥ËøòÊòØÈ¢ùÂ§ñÊãìÂ±ïÔºüÊúâÊòéÊòæÊïàÊûúÂêóÔºü/ÂØπÂ≠©Â≠êÊúâÂ∏ÆÂä©ÂêóÔºü', 'answer': 'FGDFG'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπË¥®', 'question_type': 2, 'question': 'ËØ∑ÂõûÂøÜÊúÄËøë‰∏ÄÊ¨°ÂíåÂêåÂ≠¶/ÊúãÂèãÂèëÁîü‰∏çÊÑâÂø´ÁöÑ‰∫ãÊÉÖÔºåÊèèËø∞‰∏Ä‰∏ãÁªèËøá„ÄÇÔºà40-90ÁßíÔºâ', 'answer': 'ÂìáÔºåËµ∞ÂïäËµ∞ÂïäÔºåËµ∞ÂïäËµ∞„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶‰∏öË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúÄÂñúÊ¨¢ÁöÑÂ≠¶ÁßëÊòØÂì™‰∏Ä‰∏™Ôºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢ÔºüÊúâÂèÇÂä†ËøáÂ≠¶ÁßëÁ´ûËµõÂêóÔºüÊòØ‰ªÄ‰πàÁ´ûËµõÔºüÊúâÊãøÂà∞Â•ñÈ°πÂêóÔºü', 'answer': 'ÂΩïÈü≥ÂºÄÂßãÔºåËØ≠Èü≥ËØÜÂà´Â∑≤ÂºÄÂêØ„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶ËÉΩË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúâÂ§öÂ∞ë‰∏™Â≠¶ÁßëË°•‰π†Áè≠ÔºüË°•‰π†ÁöÑÂÜÖÂÆπÊòØÊ†°ÂÜÖÁõ∏ÂÖ≥ËøòÊòØÈ¢ùÂ§ñÊãìÂ±ïÔºüÊúâÊòéÊòæÊïàÊûúÂêóÔºü/ÂØπÂ≠©Â≠êÊúâÂ∏ÆÂä©ÂêóÔºü', 'answer': 'ÂΩïÈü≥ÊùÉÈôêÂ∑≤ÊèêÂâçËé∑ÂèñÔºåÂΩïÈü≥ÂºÄÂßãÂæÆÂçöÊêúkÁâπÊÑèÂª∫Á´ã‰øÆÊ≠£„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': 'ÁªºÂêàÁ¥†Ë¥®', 'question_type': 2, 'question': '‰Ω†/Â≠©Â≠êÂπ≥Êó∂ÊúÄÂñúÊ¨¢ÁöÑÊ¥ªÂä®ÊàñÂ≠¶ÁßëÊòØ‰ªÄ‰πàÔºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢Ôºü', 'answer': '‰Ω†Âπ≥Êó∂ÊúÄÂñúÊ¨¢ÁöÑÊ¥ªÂä®‰∏∫ÁßëÂ≠¶ÊòØ‰ªÄ‰πàÔºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢Ôºü'}]
input_check_result: False
eval_result [{'question_section_name': '‰ΩìËÇ≤Ëâ∫ÊúØ', 'question_type': 2, 'question': 'ËØ∑ÊèèËø∞‰∏Ä‰∏ãÂ≠©Â≠êËá™Â∑±ÊúÄËøë‰∏ÄÊ¨°Âú®‰ΩìËÇ≤ÊàñËâ∫ÊúØÊñπÈù¢ÂùöÊåÅÁªÉ‰π†ÊàñÂàõ‰ΩúÁöÑÁªèÂéÜÔºüÊòØ‰ªÄ‰πàËÆ©‰Ω†ÂùöÊåÅ‰∏ãÂéªÁöÑÔºü', 'answer': 'ÊúÄÂêé‰∏ÄÈÅìÈ¢òÂéªÊñ∞ÁñÜ„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': 'ÊÄßÊ†ºÁâπË¥®', 'question_type': 2, 'question': 'ËØ∑ÂõûÂøÜÊúÄËøë‰∏ÄÊ¨°ÂíåÂêåÂ≠¶/ÊúãÂèãÂèëÁîü‰∏çÊÑâÂø´ÁöÑ‰∫ãÊÉÖÔºåÊèèËø∞‰∏Ä‰∏ãÁªèËøá„ÄÇÔºà40-90ÁßíÔºâ', 'answer': 'ÊÄßÊ†ºÁâπË¥®„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶‰∏öË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúÄÂñúÊ¨¢ÁöÑÂ≠¶ÁßëÊòØÂì™‰∏Ä‰∏™Ôºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢ÔºüÊúâÂèÇÂä†ËøáÂ≠¶ÁßëÁ´ûËµõÂêóÔºüÊòØ‰ªÄ‰πàÁ´ûËµõÔºüÊúâÊãøÂà∞Â•ñÈ°πÂêóÔºü', 'answer': 'ËøôÊòØËØ¥ËØùÁöÑÊó∂ÂÄô'}]
input_check_result: False
eval_result [{'question_section_name': 'Â≠¶ËÉΩË°®Áé∞', 'question_type': 2, 'question': 'Â≠©Â≠êÊúâÂ§öÂ∞ë‰∏™Â≠¶ÁßëË°•‰π†Áè≠ÔºüË°•‰π†ÁöÑÂÜÖÂÆπÊòØÊ†°ÂÜÖÁõ∏ÂÖ≥ËøòÊòØÈ¢ùÂ§ñÊãìÂ±ïÔºüÊúâÊòéÊòæÊïàÊûúÂêóÔºü/ÂØπÂ≠©Â≠êÊúâÂ∏ÆÂä©ÂêóÔºü', 'answer': 'Ëµ∞ÂïäËµ∞Ëµ∞Âà∞Á≠âÁ≠âÔºåÂá°ÊòØÁ≠æÂêçÊú™Êä•Â§á„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': 'ÁªºÂêàÁ¥†Ë¥®', 'question_type': 2, 'question': '‰Ω†/Â≠©Â≠êÂπ≥Êó∂ÊúÄÂñúÊ¨¢ÁöÑÊ¥ªÂä®ÊàñÂ≠¶ÁßëÊòØ‰ªÄ‰πàÔºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢Ôºü', 'answer': 'ÂºÄÂßãÂΩïÈü≥ÁªºÂêàÁ¥†Ë¥®„ÄÇ‰Ω†Âπ≥Êó∂ÊúÄÂñúÊ¨¢Ê¥ªÂä®ÊàñÁßëÂ≠¶ÊòØ‰ªÄ‰πàÔºü‰∏∫‰ªÄ‰πàÂñúÊ¨¢ÔºüÊàë‰πü‰∏çÁü•ÈÅì‰∏∫‰ªÄ‰πà‰ºöÂñúÊ¨¢„ÄÇ'}]
input_check_result: False
eval_result [{'question_section_name': '‰ΩìËÇ≤Ëâ∫ÊúØ', 'question_type': 2, 'question': 'ËØ∑ÊèèËø∞‰∏Ä‰∏ãÂ≠©Â≠êËá™Â∑±ÊúÄËøë‰∏ÄÊ¨°Âú®‰ΩìËÇ≤ÊàñËâ∫ÊúØÊñπÈù¢ÂùöÊåÅÁªÉ‰π†ÊàñÂàõ‰ΩúÁöÑÁªèÂéÜÔºüÊòØ‰ªÄ‰πàËÆ©‰Ω†ÂùöÊåÅ‰∏ãÂéªÁöÑÔºü', 'answer': 'Êàë‰ºöËÆ©‰ªñÂùöÊåÅÁöÑ„ÄÇ'}]
 * Restarting with stat
Traceback (most recent call last):
  File "/root/code/ai_based_education/run_app.py", line 10, in <module>
    from main import (
  File "/root/code/ai_based_education/main.py", line 28, in <module>
    from profile_desc import (
  File "/root/code/ai_based_education/profile_desc.py", line 4, in <module>
    with open('./resource/LARS_definition.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './resource/LARS_definition.json'
